export type Service = {
  id: number;
  name: string;
  cost: number;
  time: string;
  category: string;
  status: string;
};

export const SERVICES: Service[] = [
  {"id":1,"name":"Descargar PDF de Scribd","cost":4,"time":"1–20 min","category":"Digitales","status":"Permitido solo con contenido autorizado"},
  {"id":2,"name":"Vigencia de derechos IMSS","cost":7,"time":"1–10 min","category":"IMSS","status":"Disponible"},
  {"id":3,"name":"Acta por cadena Express","cost":6,"time":"1–2 min","category":"Actas","status":"Disponible"},
  {"id":4,"name":"Acta de defunción Express","cost":6,"time":"1–2 min","category":"Actas","status":"Disponible"},
  {"id":5,"name":"Acta de nacimiento Express","cost":6,"time":"1–2 min","category":"Actas","status":"Disponible"},
  {"id":6,"name":"Acta de matrimonio Express","cost":6,"time":"1–2 min","category":"Actas","status":"Disponible"},
  {"id":7,"name":"Antecedentes estatales","cost":8,"time":"1–10 min","category":"Constancias","status":"Solo consulta legítima"},
  {"id":8,"name":"Cédula profesional","cost":12,"time":"1–20 min","category":"Educación","status":"Solo consulta o recuperación legítima"},
  {"id":9,"name":"Certificado COVID","cost":8,"time":"1–10 min","category":"Constancias","status":"Solo consulta o descarga legítima"},
  {"id":10,"name":"Certificado INEA","cost":12,"time":"1–20 min","category":"Educación","status":"Solo consulta o recuperación legítima"},
  {"id":11,"name":"Certificado escolar","cost":12,"time":"1–50 min","category":"Educación","status":"Solo consulta o recuperación legítima"},
  {"id":12,"name":"Constancia fiscal Express","cost":7,"time":"1–2 min","category":"SAT","status":"Disponible"},
  {"id":13,"name":"Constancia fiscal RFC–IDCIF","cost":7,"time":"1–5 min","category":"SAT","status":"Disponible"},
  {"id":14,"name":"CSF primera vez","cost":35,"time":"1–20 min","category":"SAT","status":"Disponible"},
  {"id":15,"name":"CURP Express","cost":1,"time":"1–5 min","category":"Actas","status":"Disponible"},
  {"id":16,"name":"Incapacidad IMSS","cost":12,"time":"1–20 min","category":"IMSS","status":"Solo consulta o descarga legítima"},
  {"id":17,"name":"Localizar RFC","cost":1,"time":"1–5 min","category":"SAT","status":"Disponible"},
  {"id":18,"name":"No derechohabiencia ISSEMYM","cost":15,"time":"1–25 min","category":"Constancias","status":"Disponible"},
  {"id":19,"name":"NSS completo (2 hojas)","cost":10,"time":"1–10 min","category":"IMSS","status":"Disponible"},
  {"id":20,"name":"Número de Seguro Social (hoja)","cost":6,"time":"1–15 min","category":"IMSS","status":"Disponible"},
  {"id":21,"name":"Receta IMSS","cost":9,"time":"1–30 min","category":"IMSS","status":"Solo consulta o descarga legítima"},
  {"id":22,"name":"Título universitario","cost":12,"time":"1–50 min","category":"Educación","status":"Solo consulta o recuperación legítima"},
  {"id":23,"name":"Bot de CSF","cost":130,"time":"1–50 min","category":"Bots","status":"Revisar autorización y términos"},
  {"id":24,"name":"Estado histórico INFONAVIT","cost":50,"time":"1–3 h","category":"INFONAVIT","status":"Disponible"},
  {"id":25,"name":"Paquete de 10 correos Outlook","cost":80,"time":"1–30 min","category":"Digitales","status":"Revisar términos de servicio"},
  {"id":26,"name":"Antecedente federal","cost":12,"time":"1–10 min","category":"Constancias","status":"Solo consulta legítima"},
  {"id":27,"name":"Bot de actas","cost":270,"time":"1–3 h","category":"Bots","status":"Revisar autorización y términos"},
  {"id":28,"name":"Canva 12 meses","cost":20,"time":"1–20 min","category":"Suscripciones","status":"Revisar términos de servicio"},
  {"id":29,"name":"Canva 2 años","cost":30,"time":"1–30 min","category":"Suscripciones","status":"Revisar términos de servicio"},
  {"id":30,"name":"Canva 6 meses","cost":15,"time":"1–30 min","category":"Suscripciones","status":"Revisar términos de servicio"},
  {"id":31,"name":"Canva invitación 1 mes","cost":3,"time":"1–30 min","category":"Suscripciones","status":"Revisar términos de servicio"},
  {"id":32,"name":"Cita de pasaporte — renovación","cost":30,"time":"1–4 h","category":"Citas","status":"Disponible"},
  {"id":33,"name":"Clonar documento con foto","cost":280,"time":"1–3 días","category":"Restringidos","status":"No ofrecer"},
  {"id":34,"name":"Constancia de concubinato","cost":60,"time":"1–5 h","category":"Constancias","status":"Solo trámite oficial legítimo"},
  {"id":35,"name":"Constancia de datos fiscales","cost":18,"time":"1–5 min","category":"SAT","status":"Disponible"},
  {"id":36,"name":"Consulta de película","cost":3,"time":"1–50 min","category":"Digitales","status":"Disponible"},
  {"id":37,"name":"CSF de oficina (original)","cost":180,"time":"24–48 h","category":"SAT","status":"Disponible"},
  {"id":38,"name":"Cuenta bancaria a nombre de terceros","cost":80,"time":"1–24 h","category":"Restringidos","status":"No ofrecer"},
  {"id":39,"name":"Cuenta bancaria para recibir dinero","cost":40,"time":"1–24 h","category":"Restringidos","status":"No ofrecer"},
  {"id":40,"name":"Documento de confirmación","cost":10,"time":"1–30 min","category":"Constancias","status":"Solo trámite oficial legítimo"},
  {"id":41,"name":"Hoja de discapacidad","cost":50,"time":"1–5 h","category":"Constancias","status":"Solo trámite oficial legítimo"},
  {"id":42,"name":"Hoja REPUVE","cost":10,"time":"1–15 min","category":"Vehicular","status":"Disponible"},
  {"id":43,"name":"Gemini 18 meses","cost":85,"time":"1–50 min","category":"Suscripciones","status":"Revisar términos de servicio"},
  {"id":44,"name":"INFONAVIT — desbloqueo de cuenta","cost":50,"time":"1–30 min","category":"INFONAVIT","status":"Disponible"},
  {"id":45,"name":"INFONAVIT — aviso de retención","cost":55,"time":"1–5 h","category":"INFONAVIT","status":"Disponible"},
  {"id":46,"name":"INFONAVIT — consulta de datos","cost":55,"time":"1–4 h","category":"INFONAVIT","status":"Disponible"},
  {"id":47,"name":"INFONAVIT — estado de cuenta mensual","cost":50,"time":"1–5 h","category":"INFONAVIT","status":"Disponible"},
  {"id":48,"name":"INFONAVIT — registro de cuenta nueva","cost":50,"time":"1–5 h","category":"INFONAVIT","status":"Disponible"},
  {"id":49,"name":"INFONAVIT — restablecimiento de contraseña","cost":50,"time":"1–3 h","category":"INFONAVIT","status":"Disponible"},
  {"id":50,"name":"INFONAVIT — saldo","cost":50,"time":"1–3 h","category":"INFONAVIT","status":"Disponible"},
  {"id":51,"name":"INFONAVIT — saldo detallado","cost":50,"time":"1–2 h","category":"INFONAVIT","status":"Disponible"},
  {"id":52,"name":"IPTV Pro 1 mes","cost":35,"time":"1–10 min","category":"Suscripciones","status":"Solo contenido autorizado"},
  {"id":53,"name":"Likes para TikTok (1,000)","cost":30,"time":"1–50 min","category":"Redes","status":"Revisar términos de la plataforma"},
  {"id":54,"name":"Likes para Facebook (1,000)","cost":30,"time":"1–30 min","category":"Redes","status":"Revisar términos de la plataforma"},
  {"id":55,"name":"Likes para Instagram (1,000)","cost":30,"time":"1–50 min","category":"Redes","status":"Revisar términos de la plataforma"},
  {"id":56,"name":"Localización de IDCIF","cost":65,"time":"1–30 min","category":"SAT","status":"Disponible"},
  {"id":57,"name":"Localizar AFORE","cost":10,"time":"1–15 min","category":"Constancias","status":"Disponible"},
  {"id":58,"name":"Microsoft 365 — 12 meses","cost":90,"time":"1–30 min","category":"Suscripciones","status":"Revisar términos de servicio"},
  {"id":59,"name":"No derechohabiencia IMSS","cost":20,"time":"1–25 min","category":"IMSS","status":"Disponible"},
  {"id":60,"name":"No derechohabiencia ISSSTE","cost":20,"time":"1–25 min","category":"Constancias","status":"Disponible"},
  {"id":61,"name":"No deudor alimentario EDOMEX","cost":15,"time":"1–15 min","category":"Constancias","status":"Disponible"},
  {"id":62,"name":"No deudor alimentario federal","cost":15,"time":"1–15 min","category":"Constancias","status":"Disponible"},
  {"id":63,"name":"NordVPN 1 mes","cost":50,"time":"1–30 min","category":"Suscripciones","status":"Revisar términos de servicio"},
  {"id":64,"name":"NSS primera vez","cost":15,"time":"1–30 min","category":"IMSS","status":"Disponible"},
  {"id":65,"name":"Opinión de cumplimiento","cost":20,"time":"1–10 min","category":"SAT","status":"Disponible"},
  {"id":66,"name":"Paquete de 40 actas para bot","cost":360,"time":"1–30 min","category":"Bots","status":"Revisar autorización y términos"},
  {"id":67,"name":"Paquete de 30 actas para bot","cost":270,"time":"1–30 min","category":"Bots","status":"Revisar autorización y términos"},
  {"id":68,"name":"Permiso para circular sin placas","cost":50,"time":"1–50 min","category":"Vehicular","status":"Solo trámite oficial legítimo"},
  {"id":69,"name":"Recibo CFE rápido","cost":4,"time":"1–15 min","category":"Servicios","status":"Disponible"},
  {"id":70,"name":"Recibo CFE Fast","cost":4,"time":"1–10 min","category":"Servicios","status":"Disponible"},
  {"id":71,"name":"Registro de línea telefónica","cost":380,"time":"1–30 min","category":"Servicios","status":"Solo con titular y autorización"},
  {"id":72,"name":"Reporte de Buró de Crédito","cost":260,"time":"1–24 h","category":"Finanzas","status":"Solo con autorización del titular"},
  {"id":73,"name":"Seguidores Facebook (1,000)","cost":30,"time":"1–50 min","category":"Redes","status":"Revisar términos de la plataforma"},
  {"id":74,"name":"Seguidores Instagram (1,000)","cost":30,"time":"1–50 min","category":"Redes","status":"Revisar términos de la plataforma"},
  {"id":75,"name":"Semanas cotizadas detalladas","cost":35,"time":"1–3 h","category":"IMSS","status":"Disponible"},
  {"id":76,"name":"Servicio de doxeo","cost":150,"time":"1–24 h","category":"Restringidos","status":"No ofrecer"},
  {"id":77,"name":"SINDO alfanumérico","cost":45,"time":"1–50 min","category":"IMSS","status":"Solo consulta legítima"},
  {"id":78,"name":"SINDO último retiro","cost":45,"time":"1–50 min","category":"IMSS","status":"Solo consulta legítima"},
  {"id":79,"name":"SINDO vigencia de derechos","cost":45,"time":"1–50 min","category":"IMSS","status":"Solo consulta legítima"},
  {"id":80,"name":"Sistema Yoda — semana","cost":150,"time":"1–3 h","category":"Bots","status":"Revisar autorización y términos"},
  {"id":81,"name":"Spotify 1 mes","cost":40,"time":"1–15 min","category":"Suscripciones","status":"Revisar términos de servicio"},
  {"id":82,"name":"Talón de pago ISSSTE","cost":10,"time":"1–25 min","category":"Constancias","status":"Solo con autorización del titular"},
  {"id":83,"name":"Tenencia vehicular CDMX","cost":15,"time":"1–30 min","category":"Vehicular","status":"Disponible"},
  {"id":84,"name":"Tenencia vehicular EDOMEX","cost":15,"time":"1–30 min","category":"Vehicular","status":"Disponible"},
  {"id":85,"name":"Vistas para Instagram (1,000)","cost":10,"time":"1–50 min","category":"Redes","status":"Revisar términos de la plataforma"},
  {"id":86,"name":"ViX Premium — 1 año","cost":35,"time":"1–15 min","category":"Suscripciones","status":"Revisar términos de servicio"},
  {"id":87,"name":"Cita de pasaporte — primera vez","cost":20,"time":"1–2 h","category":"Citas","status":"Disponible"},
  {"id":88,"name":"Inexistencia de matrimonio","cost":100,"time":"1–5 h","category":"Constancias","status":"Solo trámite oficial legítimo"},
];

export const EDIT_PASSWORD = "1234";