/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TramitesRouteImport } from './routes/tramites'
import { Route as StreamingRouteImport } from './routes/streaming'
import { Route as ConsultarRouteImport } from './routes/consultar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AdminRevendedoresRouteImport } from './routes/admin/revendedores'
import { Route as AdminReportesRouteImport } from './routes/admin/reportes'
import { Route as AdminPedidosRouteImport } from './routes/admin/pedidos'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCuentasRouteImport } from './routes/admin/cuentas'
import { Route as AdminClientesRouteImport } from './routes/admin/clientes'
import { Route as AdminAnunciosRouteImport } from './routes/admin/anuncios'

const TramitesRoute = TramitesRouteImport.update({
  id: '/tramites',
  path: '/tramites',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamingRoute = StreamingRouteImport.update({
  id: '/streaming',
  path: '/streaming',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultarRoute = ConsultarRouteImport.update({
  id: '/consultar',
  path: '/consultar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevendedoresRoute = AdminRevendedoresRouteImport.update({
  id: '/revendedores',
  path: '/revendedores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportesRoute = AdminReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuentasRoute = AdminCuentasRouteImport.update({
  id: '/cuentas',
  path: '/cuentas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnunciosRoute = AdminAnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consultar': typeof ConsultarRoute
  '/streaming': typeof StreamingRoute
  '/tramites': typeof TramitesRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/cuentas': typeof AdminCuentasRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/revendedores': typeof AdminRevendedoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consultar': typeof ConsultarRoute
  '/streaming': typeof StreamingRoute
  '/tramites': typeof TramitesRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/cuentas': typeof AdminCuentasRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/revendedores': typeof AdminRevendedoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consultar': typeof ConsultarRoute
  '/streaming': typeof StreamingRoute
  '/tramites': typeof TramitesRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/cuentas': typeof AdminCuentasRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/revendedores': typeof AdminRevendedoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consultar'
    | '/streaming'
    | '/tramites'
    | '/admin/anuncios'
    | '/admin/clientes'
    | '/admin/cuentas'
    | '/admin/dashboard'
    | '/admin/pedidos'
    | '/admin/reportes'
    | '/admin/revendedores'
    | '/admin/usuarios'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consultar'
    | '/streaming'
    | '/tramites'
    | '/admin/anuncios'
    | '/admin/clientes'
    | '/admin/cuentas'
    | '/admin/dashboard'
    | '/admin/pedidos'
    | '/admin/reportes'
    | '/admin/revendedores'
    | '/admin/usuarios'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/consultar'
    | '/streaming'
    | '/tramites'
    | '/admin/anuncios'
    | '/admin/clientes'
    | '/admin/cuentas'
    | '/admin/dashboard'
    | '/admin/pedidos'
    | '/admin/reportes'
    | '/admin/revendedores'
    | '/admin/usuarios'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsultarRoute: typeof ConsultarRoute
  StreamingRoute: typeof StreamingRoute
  TramitesRoute: typeof TramitesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tramites': {
      id: '/tramites'
      path: '/tramites'
      fullPath: '/tramites'
      preLoaderRoute: typeof TramitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streaming': {
      id: '/streaming'
      path: '/streaming'
      fullPath: '/streaming'
      preLoaderRoute: typeof StreamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultar': {
      id: '/consultar'
      path: '/consultar'
      fullPath: '/consultar'
      preLoaderRoute: typeof ConsultarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revendedores': {
      id: '/admin/revendedores'
      path: '/revendedores'
      fullPath: '/admin/revendedores'
      preLoaderRoute: typeof AdminRevendedoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reportes': {
      id: '/admin/reportes'
      path: '/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AdminReportesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cuentas': {
      id: '/admin/cuentas'
      path: '/cuentas'
      fullPath: '/admin/cuentas'
      preLoaderRoute: typeof AdminCuentasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/anuncios': {
      id: '/admin/anuncios'
      path: '/anuncios'
      fullPath: '/admin/anuncios'
      preLoaderRoute: typeof AdminAnunciosRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsultarRoute: ConsultarRoute,
  StreamingRoute: StreamingRoute,
  TramitesRoute: TramitesRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
