/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TramitesRouteImport } from './routes/tramites'
import { Route as StreamingRouteImport } from './routes/streaming'
import { Route as ConsultarRouteImport } from './routes/consultar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntregaTokenRouteImport } from './routes/entrega.$token'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminSeguridadRouteImport } from './routes/_authenticated/admin/seguridad'
import { Route as AuthenticatedAdminRevendedoresRouteImport } from './routes/_authenticated/admin/revendedores'
import { Route as AuthenticatedAdminReportesRouteImport } from './routes/_authenticated/admin/reportes'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin/pedidos'
import { Route as AuthenticatedAdminEntregasRouteImport } from './routes/_authenticated/admin/entregas'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminCuentasRouteImport } from './routes/_authenticated/admin/cuentas'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin/clientes'
import { Route as AuthenticatedAdminAnunciosRouteImport } from './routes/_authenticated/admin/anuncios'

const TramitesRoute = TramitesRouteImport.update({
  id: '/tramites',
  path: '/tramites',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamingRoute = StreamingRouteImport.update({
  id: '/streaming',
  path: '/streaming',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultarRoute = ConsultarRouteImport.update({
  id: '/consultar',
  path: '/consultar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregaTokenRoute = EntregaTokenRouteImport.update({
  id: '/entrega/$token',
  path: '/entrega/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSeguridadRoute =
  AuthenticatedAdminSeguridadRouteImport.update({
    id: '/seguridad',
    path: '/seguridad',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRevendedoresRoute =
  AuthenticatedAdminRevendedoresRouteImport.update({
    id: '/revendedores',
    path: '/revendedores',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReportesRoute =
  AuthenticatedAdminReportesRouteImport.update({
    id: '/reportes',
    path: '/reportes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEntregasRoute =
  AuthenticatedAdminEntregasRouteImport.update({
    id: '/entregas',
    path: '/entregas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCuentasRoute =
  AuthenticatedAdminCuentasRouteImport.update({
    id: '/cuentas',
    path: '/cuentas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnunciosRoute =
  AuthenticatedAdminAnunciosRouteImport.update({
    id: '/anuncios',
    path: '/anuncios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/consultar': typeof ConsultarRoute
  '/streaming': typeof StreamingRoute
  '/tramites': typeof TramitesRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/entrega/$token': typeof EntregaTokenRoute
  '/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/cuentas': typeof AuthenticatedAdminCuentasRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/entregas': typeof AuthenticatedAdminEntregasRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/admin/revendedores': typeof AuthenticatedAdminRevendedoresRoute
  '/admin/seguridad': typeof AuthenticatedAdminSeguridadRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/consultar': typeof ConsultarRoute
  '/streaming': typeof StreamingRoute
  '/tramites': typeof TramitesRoute
  '/entrega/$token': typeof EntregaTokenRoute
  '/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/cuentas': typeof AuthenticatedAdminCuentasRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/entregas': typeof AuthenticatedAdminEntregasRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/admin/revendedores': typeof AuthenticatedAdminRevendedoresRoute
  '/admin/seguridad': typeof AuthenticatedAdminSeguridadRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/consultar': typeof ConsultarRoute
  '/streaming': typeof StreamingRoute
  '/tramites': typeof TramitesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/entrega/$token': typeof EntregaTokenRoute
  '/_authenticated/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/cuentas': typeof AuthenticatedAdminCuentasRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/entregas': typeof AuthenticatedAdminEntregasRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/_authenticated/admin/revendedores': typeof AuthenticatedAdminRevendedoresRoute
  '/_authenticated/admin/seguridad': typeof AuthenticatedAdminSeguridadRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/consultar'
    | '/streaming'
    | '/tramites'
    | '/admin'
    | '/entrega/$token'
    | '/admin/anuncios'
    | '/admin/clientes'
    | '/admin/cuentas'
    | '/admin/dashboard'
    | '/admin/entregas'
    | '/admin/pedidos'
    | '/admin/reportes'
    | '/admin/revendedores'
    | '/admin/seguridad'
    | '/admin/usuarios'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/consultar'
    | '/streaming'
    | '/tramites'
    | '/entrega/$token'
    | '/admin/anuncios'
    | '/admin/clientes'
    | '/admin/cuentas'
    | '/admin/dashboard'
    | '/admin/entregas'
    | '/admin/pedidos'
    | '/admin/reportes'
    | '/admin/revendedores'
    | '/admin/seguridad'
    | '/admin/usuarios'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/consultar'
    | '/streaming'
    | '/tramites'
    | '/_authenticated/admin'
    | '/entrega/$token'
    | '/_authenticated/admin/anuncios'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/cuentas'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/entregas'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/reportes'
    | '/_authenticated/admin/revendedores'
    | '/_authenticated/admin/seguridad'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConsultarRoute: typeof ConsultarRoute
  StreamingRoute: typeof StreamingRoute
  TramitesRoute: typeof TramitesRoute
  EntregaTokenRoute: typeof EntregaTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tramites': {
      id: '/tramites'
      path: '/tramites'
      fullPath: '/tramites'
      preLoaderRoute: typeof TramitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streaming': {
      id: '/streaming'
      path: '/streaming'
      fullPath: '/streaming'
      preLoaderRoute: typeof StreamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultar': {
      id: '/consultar'
      path: '/consultar'
      fullPath: '/consultar'
      preLoaderRoute: typeof ConsultarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrega/$token': {
      id: '/entrega/$token'
      path: '/entrega/$token'
      fullPath: '/entrega/$token'
      preLoaderRoute: typeof EntregaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/seguridad': {
      id: '/_authenticated/admin/seguridad'
      path: '/seguridad'
      fullPath: '/admin/seguridad'
      preLoaderRoute: typeof AuthenticatedAdminSeguridadRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/revendedores': {
      id: '/_authenticated/admin/revendedores'
      path: '/revendedores'
      fullPath: '/admin/revendedores'
      preLoaderRoute: typeof AuthenticatedAdminRevendedoresRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reportes': {
      id: '/_authenticated/admin/reportes'
      path: '/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AuthenticatedAdminReportesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/entregas': {
      id: '/_authenticated/admin/entregas'
      path: '/entregas'
      fullPath: '/admin/entregas'
      preLoaderRoute: typeof AuthenticatedAdminEntregasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cuentas': {
      id: '/_authenticated/admin/cuentas'
      path: '/cuentas'
      fullPath: '/admin/cuentas'
      preLoaderRoute: typeof AuthenticatedAdminCuentasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/anuncios': {
      id: '/_authenticated/admin/anuncios'
      path: '/anuncios'
      fullPath: '/admin/anuncios'
      preLoaderRoute: typeof AuthenticatedAdminAnunciosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnunciosRoute: typeof AuthenticatedAdminAnunciosRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminCuentasRoute: typeof AuthenticatedAdminCuentasRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminEntregasRoute: typeof AuthenticatedAdminEntregasRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminReportesRoute: typeof AuthenticatedAdminReportesRoute
  AuthenticatedAdminRevendedoresRoute: typeof AuthenticatedAdminRevendedoresRoute
  AuthenticatedAdminSeguridadRoute: typeof AuthenticatedAdminSeguridadRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnunciosRoute: AuthenticatedAdminAnunciosRoute,
    AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
    AuthenticatedAdminCuentasRoute: AuthenticatedAdminCuentasRoute,
    AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
    AuthenticatedAdminEntregasRoute: AuthenticatedAdminEntregasRoute,
    AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
    AuthenticatedAdminReportesRoute: AuthenticatedAdminReportesRoute,
    AuthenticatedAdminRevendedoresRoute: AuthenticatedAdminRevendedoresRoute,
    AuthenticatedAdminSeguridadRoute: AuthenticatedAdminSeguridadRoute,
    AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConsultarRoute: ConsultarRoute,
  StreamingRoute: StreamingRoute,
  TramitesRoute: TramitesRoute,
  EntregaTokenRoute: EntregaTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
