/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TramitesRouteImport } from './routes/tramites'
import { Route as StreamingRouteImport } from './routes/streaming'
import { Route as ConsultarRouteImport } from './routes/consultar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntregaTokenRouteImport } from './routes/entrega.$token'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminRevendedoresRouteImport } from './routes/_authenticated/admin/revendedores'
import { Route as AuthenticatedAdminReportesRouteImport } from './routes/_authenticated/admin/reportes'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin/pedidos'
import { Route as AuthenticatedAdminEntregasRouteImport } from './routes/_authenticated/admin/entregas'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminCuentasRouteImport } from './routes/_authenticated/admin/cuentas'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin/clientes'
import { Route as AuthenticatedAdminAnunciosRouteImport } from './routes/_authenticated/admin/anuncios'

const TramitesRoute = TramitesRouteImport.update({
  id: '/tramites',
  path: '/tramites',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamingRoute = StreamingRouteImport.update({
  id: '/streaming',
  path: '/streaming',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultarRoute = ConsultarRouteImport.update({
  id: '/consultar',
  path: '/consultar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregaTokenRoute = EntregaTokenRouteImport.update({
  id: '/entrega/$token',
  path: '/entrega/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/_authenticated/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/_authenticated/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRevendedoresRoute =
  AuthenticatedAdminRevendedoresRouteImport.update({
    id: '/_authenticated/admin/revendedores',
    path: '/admin/revendedores',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminReportesRoute =
  AuthenticatedAdminReportesRouteImport.update({
    id: '/_authenticated/admin/reportes',
    path: '/admin/reportes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/_authenticated/admin/pedidos',
    path: '/admin/pedidos',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminEntregasRoute =
  AuthenticatedAdminEntregasRouteImport.update({
    id: '/_authenticated/admin/entregas',
    path: '/admin/entregas',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/_authenticated/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminCuentasRoute =
  AuthenticatedAdminCuentasRouteImport.update({
    id: '/_authenticated/admin/cuentas',
    path: '/admin/cuentas',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/_authenticated/admin/clientes',
    path: '/admin/clientes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminAnunciosRoute =
  AuthenticatedAdminAnunciosRouteImport.update({
    id: '/_authenticated/admin/anuncios',
    path: '/admin/anuncios',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consultar': typeof ConsultarRoute
  '/streaming': typeof StreamingRoute
  '/tramites': typeof TramitesRoute
  '/entrega/$token': typeof EntregaTokenRoute
  '/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/cuentas': typeof AuthenticatedAdminCuentasRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/entregas': typeof AuthenticatedAdminEntregasRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/admin/revendedores': typeof AuthenticatedAdminRevendedoresRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consultar': typeof ConsultarRoute
  '/streaming': typeof StreamingRoute
  '/tramites': typeof TramitesRoute
  '/entrega/$token': typeof EntregaTokenRoute
  '/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/cuentas': typeof AuthenticatedAdminCuentasRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/entregas': typeof AuthenticatedAdminEntregasRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/admin/revendedores': typeof AuthenticatedAdminRevendedoresRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consultar': typeof ConsultarRoute
  '/streaming': typeof StreamingRoute
  '/tramites': typeof TramitesRoute
  '/entrega/$token': typeof EntregaTokenRoute
  '/_authenticated/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/cuentas': typeof AuthenticatedAdminCuentasRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/entregas': typeof AuthenticatedAdminEntregasRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/_authenticated/admin/revendedores': typeof AuthenticatedAdminRevendedoresRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consultar'
    | '/streaming'
    | '/tramites'
    | '/entrega/$token'
    | '/admin/anuncios'
    | '/admin/clientes'
    | '/admin/cuentas'
    | '/admin/dashboard'
    | '/admin/entregas'
    | '/admin/pedidos'
    | '/admin/reportes'
    | '/admin/revendedores'
    | '/admin/usuarios'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consultar'
    | '/streaming'
    | '/tramites'
    | '/entrega/$token'
    | '/admin/anuncios'
    | '/admin/clientes'
    | '/admin/cuentas'
    | '/admin/dashboard'
    | '/admin/entregas'
    | '/admin/pedidos'
    | '/admin/reportes'
    | '/admin/revendedores'
    | '/admin/usuarios'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/consultar'
    | '/streaming'
    | '/tramites'
    | '/entrega/$token'
    | '/_authenticated/admin/anuncios'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/cuentas'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/entregas'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/reportes'
    | '/_authenticated/admin/revendedores'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsultarRoute: typeof ConsultarRoute
  StreamingRoute: typeof StreamingRoute
  TramitesRoute: typeof TramitesRoute
  EntregaTokenRoute: typeof EntregaTokenRoute
  AuthenticatedAdminAnunciosRoute: typeof AuthenticatedAdminAnunciosRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminCuentasRoute: typeof AuthenticatedAdminCuentasRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminEntregasRoute: typeof AuthenticatedAdminEntregasRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminReportesRoute: typeof AuthenticatedAdminReportesRoute
  AuthenticatedAdminRevendedoresRoute: typeof AuthenticatedAdminRevendedoresRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tramites': {
      id: '/tramites'
      path: '/tramites'
      fullPath: '/tramites'
      preLoaderRoute: typeof TramitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streaming': {
      id: '/streaming'
      path: '/streaming'
      fullPath: '/streaming'
      preLoaderRoute: typeof StreamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultar': {
      id: '/consultar'
      path: '/consultar'
      fullPath: '/consultar'
      preLoaderRoute: typeof ConsultarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrega/$token': {
      id: '/entrega/$token'
      path: '/entrega/$token'
      fullPath: '/entrega/$token'
      preLoaderRoute: typeof EntregaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/revendedores': {
      id: '/_authenticated/admin/revendedores'
      path: '/admin/revendedores'
      fullPath: '/admin/revendedores'
      preLoaderRoute: typeof AuthenticatedAdminRevendedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/reportes': {
      id: '/_authenticated/admin/reportes'
      path: '/admin/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AuthenticatedAdminReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/entregas': {
      id: '/_authenticated/admin/entregas'
      path: '/admin/entregas'
      fullPath: '/admin/entregas'
      preLoaderRoute: typeof AuthenticatedAdminEntregasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/cuentas': {
      id: '/_authenticated/admin/cuentas'
      path: '/admin/cuentas'
      fullPath: '/admin/cuentas'
      preLoaderRoute: typeof AuthenticatedAdminCuentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/admin/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/anuncios': {
      id: '/_authenticated/admin/anuncios'
      path: '/admin/anuncios'
      fullPath: '/admin/anuncios'
      preLoaderRoute: typeof AuthenticatedAdminAnunciosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsultarRoute: ConsultarRoute,
  StreamingRoute: StreamingRoute,
  TramitesRoute: TramitesRoute,
  EntregaTokenRoute: EntregaTokenRoute,
  AuthenticatedAdminAnunciosRoute: AuthenticatedAdminAnunciosRoute,
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminCuentasRoute: AuthenticatedAdminCuentasRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminEntregasRoute: AuthenticatedAdminEntregasRoute,
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
  AuthenticatedAdminReportesRoute: AuthenticatedAdminReportesRoute,
  AuthenticatedAdminRevendedoresRoute: AuthenticatedAdminRevendedoresRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
